import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/*
*   This is our main class. It takes in two arguments: customer type
*   and total bill. It then displays the total discount availed and
*   the net payable bill.
*/

public class BillTest {

    public static void main (String[]args){ 
       
    		Customer customer;
        Bill bill;
        float totalBill, groceryBill;
        PrintWriter out = null;
        
        try {
        		out = new PrintWriter(new FileWriter("OutFile.txt"));
        } catch (IOException e) {
        	
        }
        
        out.println("This is the report generated by running the test file BillTest.java.");
        out.println("Customer Types: 4, Tests for each: 10, Total Tests: 40");
        out.print("------------------------------------------------------------\n");
        
        //------------------- TEST PARAMETERS --------------------//
        String [] customerTypes = new String []{"Employee", "Affiliate", "Regular", "none of the above"};
        float [] totalBills = new float [] {10f, 20f, 40f, 80f, 160f, 320f, 640f, 1280f, 2560f, 5120f};
        float [] groceryBills = new float []{0f, 10f, 20f, 30f, 50f, 100f, 250f, 500f, 1000f, 2000f};

        for (int i = 0; i<customerTypes.length;i++){
            customer = getCustomer(customerTypes[i]);
            out.print("Customer Type: ");
            out.println(customerTypes[i]);
            out.print("\n");
            for (int j = 0; j<10; j++){
                totalBill = totalBills[j];
                groceryBill = groceryBills[j];

                /*
                *   Creates the bill (object) and finds the total discount
                */ 
                bill = new Bill(customer, totalBill, groceryBill);
                displayResults(bill, totalBill, groceryBill, out);

            }
            out.println("---------------------------------------");
            out.print("\n");
        }
        
        out.close();
        
    }

    private static Customer getCustomer(String s){
        
        Customer c;
        switch(s.toLowerCase()) {       
            case "employee":
                c = new Employee();
                break;

            case "affiliate":
                c = new Affiliate();
                break;
            case "regular":
                   c = new RegularCustomer();
                   break;
            default:
             c = new Customer();          
        }

        return c;
    }

    private static void displayResults(Bill b, float f, float g, PrintWriter out){
		out.print("Total Bill is: ");
		out.println(f);
		out.print("Grocery Bill is: ");
		out.println(g);
        out.print("Payable Bill is: ");
        out.printf("%.2f\n", f-b.totalDiscount());
        out.print("Total discount availed: ");
        out.printf("%.2f\n\n", b.totalDiscount());
        
    }

}
